java simulator.framework.Elevator -cf sd1a.cf -mf sd1a.mf
java simulator.framework.Elevator -cf sd1b.cf -mf sd1b.mf
java simulator.framework.Elevator -cf sd1c.cf -mf sd1c.mf
java simulator.framework.Elevator -cf sd1d.cf -mf sd1d.mf
java simulator.framework.Elevator -cf sd2a.cf -mf sd2a.mf
java simulator.framework.Elevator -cf sd2b.cf -mf sd2b.mf
java simulator.framework.Elevator -cf sd2c.cf -mf sd2c.mf
java simulator.framework.Elevator -cf sd2d.cf -mf sd2d.mf
java simulator.framework.Elevator -cf sd3a.cf -mf sd3a.mf
java simulator.framework.Elevator -cf sd3b.cf -mf sd3b.mf
java simulator.framework.Elevator -cf sd4a.cf -mf sd4a.mf
java simulator.framework.Elevator -cf sd4b.cf -mf sd4b.mf
java simulator.framework.Elevator -cf sd5a.cf -mf sd5a.mf
java simulator.framework.Elevator -cf sd5b.cf -mf sd5b.mf
java simulator.framework.Elevator -cf sd6a.cf -mf sd6a.mf
java simulator.framework.Elevator -cf sd7a.cf -mf sd7a.mf
java simulator.framework.Elevator -cf sd7b.cf -mf sd7b.mf
java simulator.framework.Elevator -cf sd7c.cf -mf sd7c.mf
java simulator.framework.Elevator -cf sd8a.cf -mf sd8a.mf
java simulator.framework.Elevator -cf sd8b.cf -mf sd8b.mf
java simulator.framework.Elevator -cf sd8c.cf -mf sd8c.mf
java simulator.framework.Elevator -cf sd9a.cf -mf sd9a.mf